In [1]:
# From our other notebook we created 5 csv files.
# we will individually load and analyze each of these files

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json
import os
import sys

In [2]:
strength_tincture_market = pd.read_csv("..\\data\\strength_tincture_market.csv")
mind_tincture_market = pd.read_csv("..\\data\\mind_tincture_market.csv")
vitality_tincture_market = pd.read_csv("..\\data\\vitality_tincture_market.csv")
dexterity_tincture_market = pd.read_csv("..\\data\\dexterity_tincture_market.csv")
intelligence_tincture_market = pd.read_csv("..\\data\\intelligence_tincture_market.csv")

In [3]:
strength_tincture_market.head()

,hq,pricePerUnit,quantity,buyerName,onMannequin,timestamp,worldName,worldID,Name,itemID,year,month,day,hour,minute,second,day_of_week,week_of_year
0,True,2989,47,Edit Undeux,False,2024-03-20 17:28:45,Faerie,54,Grade 8 Tincture of Strength,39727,2024,3,20,17,28,45,Wednesday,12
1,True,2714,99,Mythological Dream,False,2024-03-20 17:27:55,Gilgamesh,63,Grade 8 Tincture of Strength,39727,2024,3,20,17,27,55,Wednesday,12
2,True,2714,99,Mythological Dream,False,2024-03-20 17:27:53,Gilgamesh,63,Grade 8 Tincture of Strength,39727,2024,3,20,17,27,53,Wednesday,12
3,True,2714,99,Mythological Dream,False,2024-03-20 17:27:52,Gilgamesh,63,Grade 8 Tincture of Strength,39727,2024,3,20,17,27,52,Wednesday,12
4,True,2700,99,Bib Kek,False,2024-03-20 17:11:23,Gilgamesh,63,Grade 8 Tincture of Strength,39727,2024,3,20,17,11,23,Wednesday,12

In [4]:
# Break down the timestamp into year, month, day, hour, minute, second, day of the week, and week of the year
strength_tincture_market['timestamp'] = pd.to_datetime(strength_tincture_market['timestamp'])
strength_tincture_market['year'] = strength_tincture_market['timestamp'].dt.year
strength_tincture_market['month'] = strength_tincture_market['timestamp'].dt.month
strength_tincture_market['day'] = strength_tincture_market['timestamp'].dt.day
strength_tincture_market['hour'] = strength_tincture_market['timestamp'].dt.hour
strength_tincture_market['minute'] = strength_tincture_market['timestamp'].dt.minute
strength_tincture_market['second'] = strength_tincture_market['timestamp'].dt.second
strength_tincture_market['day_of_week'] = strength_tincture_market['timestamp'].dt.dayofweek
strength_tincture_market['day_of_week'] = strength_tincture_market['day_of_week'].map({0:'Monday',1:'Tuesday',2:'Wednesday',3:'Thursday',4:'Friday',5:'Saturday',6:'Sunday'})
strength_tincture_market['week_of_year'] = strength_tincture_market['timestamp'].dt.isocalendar().week
# save the data to a new csv file
strength_tincture_market.to_csv("..\\data\\strength_tincture_market.csv", index=False)

strength_tincture_market.head()

,hq,pricePerUnit,quantity,buyerName,onMannequin,timestamp,worldName,worldID,Name,itemID,year,month,day,hour,minute,second,day_of_week,week_of_year
0,True,2989,47,Edit Undeux,False,2024-03-20 17:28:45,Faerie,54,Grade 8 Tincture of Strength,39727,2024,3,20,17,28,45,Wednesday,12
1,True,2714,99,Mythological Dream,False,2024-03-20 17:27:55,Gilgamesh,63,Grade 8 Tincture of Strength,39727,2024,3,20,17,27,55,Wednesday,12
2,True,2714,99,Mythological Dream,False,2024-03-20 17:27:53,Gilgamesh,63,Grade 8 Tincture of Strength,39727,2024,3,20,17,27,53,Wednesday,12
3,True,2714,99,Mythological Dream,False,2024-03-20 17:27:52,Gilgamesh,63,Grade 8 Tincture of Strength,39727,2024,3,20,17,27,52,Wednesday,12
4,True,2700,99,Bib Kek,False,2024-03-20 17:11:23,Gilgamesh,63,Grade 8 Tincture of Strength,39727,2024,3,20,17,11,23,Wednesday,12

In [5]:
# Break down the timestamp into year, month, day, hour, minute, second, day of the week, and week of the year
mind_tincture_market['timestamp'] = pd.to_datetime(mind_tincture_market['timestamp'])
mind_tincture_market['year'] = mind_tincture_market['timestamp'].dt.year
mind_tincture_market['month'] = mind_tincture_market['timestamp'].dt.month
mind_tincture_market['day'] = mind_tincture_market['timestamp'].dt.day
mind_tincture_market['hour'] = mind_tincture_market['timestamp'].dt.hour
mind_tincture_market['minute'] = mind_tincture_market['timestamp'].dt.minute
mind_tincture_market['second'] = mind_tincture_market['timestamp'].dt.second
mind_tincture_market['day_of_week'] = mind_tincture_market['timestamp'].dt.dayofweek
mind_tincture_market['day_of_week'] = mind_tincture_market['day_of_week'].map({0:'Monday',1:'Tuesday',2:'Wednesday',3:'Thursday',4:'Friday',5:'Saturday',6:'Sunday'})
mind_tincture_market['week_of_year'] = mind_tincture_market['timestamp'].dt.isocalendar().week
# save the data to a new csv file
mind_tincture_market.to_csv("..\\data\\mind_tincture_market.csv", index=False)

mind_tincture_market.head()

,hq,pricePerUnit,quantity,buyerName,onMannequin,timestamp,worldName,worldID,Name,itemID,year,month,day,hour,minute,second,day_of_week,week_of_year
0,True,2837,50,Leandros Adastros,False,2024-03-20 11:32:32,Adamantoise,73,Grade 8 Tincture of Mind,39731,2024,3,20,11,32,32,Wednesday,12
1,True,3089,99,Ren Ryder,False,2024-03-20 08:55:08,Faerie,54,Grade 8 Tincture of Mind,39731,2024,3,20,8,55,8,Wednesday,12
2,True,2672,99,Camellia Yagami,False,2024-03-20 07:01:38,Gilgamesh,63,Grade 8 Tincture of Mind,39731,2024,3,20,7,1,38,Wednesday,12
3,True,2672,99,Camellia Yagami,False,2024-03-20 07:01:37,Gilgamesh,63,Grade 8 Tincture of Mind,39731,2024,3,20,7,1,37,Wednesday,12
4,True,2672,99,Camellia Yagami,False,2024-03-20 07:01:36,Gilgamesh,63,Grade 8 Tincture of Mind,39731,2024,3,20,7,1,36,Wednesday,12

In [6]:
# Break down the timestamp into year, month, day, hour, minute, second, day of the week, and week of the year
vitality_tincture_market['timestamp'] = pd.to_datetime(vitality_tincture_market['timestamp'])
vitality_tincture_market['year'] = vitality_tincture_market['timestamp'].dt.year
vitality_tincture_market['month'] = vitality_tincture_market['timestamp'].dt.month
vitality_tincture_market['day'] = vitality_tincture_market['timestamp'].dt.day
vitality_tincture_market['hour'] = vitality_tincture_market['timestamp'].dt.hour
vitality_tincture_market['minute'] = vitality_tincture_market['timestamp'].dt.minute
vitality_tincture_market['second'] = vitality_tincture_market['timestamp'].dt.second
vitality_tincture_market['day_of_week'] = vitality_tincture_market['timestamp'].dt.dayofweek
vitality_tincture_market['day_of_week'] = vitality_tincture_market['day_of_week'].map({0:'Monday',1:'Tuesday',2:'Wednesday',3:'Thursday',4:'Friday',5:'Saturday',6:'Sunday'})
vitality_tincture_market['week_of_year'] = vitality_tincture_market['timestamp'].dt.isocalendar().week
# save the data to a new csv file
vitality_tincture_market.to_csv("..\\data\\vitality_tincture_market.csv", index=False)

vitality_tincture_market.head()

,hq,pricePerUnit,quantity,buyerName,onMannequin,timestamp,worldName,worldID,Name,itemID,year,month,day,hour,minute,second,day_of_week,week_of_year
0,True,2974,20,Reina Uberall,False,2024-03-17 23:06:14,Gilgamesh,63,Grade 8 Tincture of Vitality,39729,2024,3,17,23,6,14,Sunday,11
1,True,1850,30,Elsha Linnette,False,2024-03-14 12:58:43,Midgardsormr,65,Grade 8 Tincture of Vitality,39729,2024,3,14,12,58,43,Thursday,11
2,True,2996,24,Samara Hana,False,2024-03-14 12:17:15,Adamantoise,73,Grade 8 Tincture of Vitality,39729,2024,3,14,12,17,15,Thursday,11
3,True,2997,99,Samara Hana,False,2024-03-14 12:17:14,Adamantoise,73,Grade 8 Tincture of Vitality,39729,2024,3,14,12,17,14,Thursday,11
4,True,2000,33,Sair Hyskaris,False,2024-03-13 16:39:09,Gilgamesh,63,Grade 8 Tincture of Vitality,39729,2024,3,13,16,39,9,Wednesday,11

In [7]:
# Break down the timestamp into year, month, day, hour, minute, second, day of the week, and week of the year
dexterity_tincture_market['timestamp'] = pd.to_datetime(dexterity_tincture_market['timestamp'])
dexterity_tincture_market['year'] = dexterity_tincture_market['timestamp'].dt.year
dexterity_tincture_market['month'] = dexterity_tincture_market['timestamp'].dt.month
dexterity_tincture_market['day'] = dexterity_tincture_market['timestamp'].dt.day
dexterity_tincture_market['hour'] = dexterity_tincture_market['timestamp'].dt.hour
dexterity_tincture_market['minute'] = dexterity_tincture_market['timestamp'].dt.minute
dexterity_tincture_market['second'] = dexterity_tincture_market['timestamp'].dt.second
dexterity_tincture_market['day_of_week'] = dexterity_tincture_market['timestamp'].dt.dayofweek
dexterity_tincture_market['day_of_week'] = dexterity_tincture_market['day_of_week'].map({0:'Monday',1:'Tuesday',2:'Wednesday',3:'Thursday',4:'Friday',5:'Saturday',6:'Sunday'})
dexterity_tincture_market['week_of_year'] = dexterity_tincture_market['timestamp'].dt.isocalendar().week
# save the data to a new csv file
dexterity_tincture_market.to_csv("..\\data\\dexterity_tincture_market.csv", index=False)

dexterity_tincture_market.head()

,hq,pricePerUnit,quantity,buyerName,onMannequin,timestamp,worldName,worldID,Name,itemID,year,month,day,hour,minute,second,day_of_week,week_of_year
0,True,2862,33,Dark Phenex,False,2024-03-20 17:40:40,Adamantoise,73,Grade 8 Tincture of Dexterity,39728,2024,3,20,17,40,40,Wednesday,12
1,True,2862,33,Dark Phenex,False,2024-03-20 17:40:37,Adamantoise,73,Grade 8 Tincture of Dexterity,39728,2024,3,20,17,40,37,Wednesday,12
2,True,2788,99,Lobotomy Victim,False,2024-03-20 16:57:28,Midgardsormr,65,Grade 8 Tincture of Dexterity,39728,2024,3,20,16,57,28,Wednesday,12
3,True,2787,99,Lobotomy Victim,False,2024-03-20 16:57:26,Midgardsormr,65,Grade 8 Tincture of Dexterity,39728,2024,3,20,16,57,26,Wednesday,12
4,True,2863,51,Lune Cr'est,False,2024-03-20 16:39:34,Adamantoise,73,Grade 8 Tincture of Dexterity,39728,2024,3,20,16,39,34,Wednesday,12

In [8]:
#break down the timestamp into year, month, day, hour, minute, second, day of the week, and week of the year
intelligence_tincture_market['timestamp'] = pd.to_datetime(intelligence_tincture_market['timestamp'])
intelligence_tincture_market['year'] = intelligence_tincture_market['timestamp'].dt.year
intelligence_tincture_market['month'] = intelligence_tincture_market['timestamp'].dt.month
intelligence_tincture_market['day'] = intelligence_tincture_market['timestamp'].dt.day
intelligence_tincture_market['hour'] = intelligence_tincture_market['timestamp'].dt.hour
intelligence_tincture_market['minute'] = intelligence_tincture_market['timestamp'].dt.minute
intelligence_tincture_market['second'] = intelligence_tincture_market['timestamp'].dt.second
intelligence_tincture_market['day_of_week'] = intelligence_tincture_market['timestamp'].dt.dayofweek
intelligence_tincture_market['day_of_week'] = intelligence_tincture_market['day_of_week'].map({0:'Monday',1:'Tuesday',2:'Wednesday',3:'Thursday',4:'Friday',5:'Saturday',6:'Sunday'})
intelligence_tincture_market['week_of_year'] = intelligence_tincture_market['timestamp'].dt.isocalendar().week
# save the data to a new csv file
intelligence_tincture_market.to_csv("..\\data\\intelligence_tincture_market.csv", index=False)

intelligence_tincture_market.head()

,hq,pricePerUnit,quantity,buyerName,onMannequin,timestamp,worldName,worldID,Name,itemID,year,month,day,hour,minute,second,day_of_week,week_of_year
0,True,2823,25,Glacial Storm,False,2024-03-20 17:04:18,Midgardsormr,65,Grade 8 Tincture of Intelligence,39730,2024,3,20,17,4,18,Wednesday,12
1,True,2823,25,Coconut Melk,False,2024-03-20 16:22:20,Midgardsormr,65,Grade 8 Tincture of Intelligence,39730,2024,3,20,16,22,20,Wednesday,12
2,False,2000,3,Deimos Drackin,False,2024-03-20 15:36:20,Gilgamesh,63,Grade 8 Tincture of Intelligence,39730,2024,3,20,15,36,20,Wednesday,12
3,False,2997,15,Deimos Drackin,False,2024-03-20 15:36:04,Gilgamesh,63,Grade 8 Tincture of Intelligence,39730,2024,3,20,15,36,4,Wednesday,12
4,True,2823,25,Faeron Evergleam,False,2024-03-20 15:13:57,Midgardsormr,65,Grade 8 Tincture of Intelligence,39730,2024,3,20,15,13,57,Wednesday,12

In [9]:
# since the columns are the same for all the dataframes, we can combine them into one dataframe
combined_tincture_market = pd.concat([strength_tincture_market, mind_tincture_market, vitality_tincture_market, dexterity_tincture_market, intelligence_tincture_market], ignore_index=True)
combined_tincture_market.to_csv("..\\data\\combined_tincture_market.csv", index=False)
combined_tincture_market.head()

,hq,pricePerUnit,quantity,buyerName,onMannequin,timestamp,worldName,worldID,Name,itemID,year,month,day,hour,minute,second,day_of_week,week_of_year
0,True,2989,47,Edit Undeux,False,2024-03-20 17:28:45,Faerie,54,Grade 8 Tincture of Strength,39727,2024,3,20,17,28,45,Wednesday,12
1,True,2714,99,Mythological Dream,False,2024-03-20 17:27:55,Gilgamesh,63,Grade 8 Tincture of Strength,39727,2024,3,20,17,27,55,Wednesday,12
2,True,2714,99,Mythological Dream,False,2024-03-20 17:27:53,Gilgamesh,63,Grade 8 Tincture of Strength,39727,2024,3,20,17,27,53,Wednesday,12
3,True,2714,99,Mythological Dream,False,2024-03-20 17:27:52,Gilgamesh,63,Grade 8 Tincture of Strength,39727,2024,3,20,17,27,52,Wednesday,12
4,True,2700,99,Bib Kek,False,2024-03-20 17:11:23,Gilgamesh,63,Grade 8 Tincture of Strength,39727,2024,3,20,17,11,23,Wednesday,12

In [10]:
combined_tincture_market.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390269 entries, 0 to 390268
Data columns (total 18 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   hq            390269 non-null  bool
 1   pricePerUnit  390269 non-null  int64
 2   quantity      390269 non-null  int64
 3   buyerName     390269 non-null  object
 4   onMannequin   390269 non-null  bool
 5   timestamp     390269 non-null  datetime64[ns]
 6   worldName     390269 non-null  object
 7   worldID       390269 non-null  int64
 8   Name          390269 non-null  object
 9   itemID        390269 non-null  int64
 10  year          390269 non-null  int32
 11  month         390269 non-null  int32
 12  day           390269 non-null  int32
 13  hour          390269 non-null  int32
 14  minute        390269 non-null  int32
 15  second        390269 non-null  int32
 16  day_of_week   390269 non-null  object
 17  week_of_year  390269 non-null  UInt32
dtypes: UInt32(1), bool(2), datetime64[ns](1), int32(6), int64(4), object(4)
memory usage: 38.3+ MB